import './globals.css';
import type { Metadata, Viewport } from 'next';
import type { ReactNode } from 'react';
import localFont from 'next/font/local';
import Link from 'next/link';
import { Suspense } from 'react';
import { auth, signOut } from '@/auth';
import { loadAccessibleNeedsYou } from '@/lib/needs-you-load';
import { headerNeedsYou } from '@/lib/needs-you';
import { loadRailData } from '@/lib/rail';
import { loadVentures } from '@/lib/ventures';
import { authorizeVentures, parseAdminEmails } from '@/lib/authz';
import { timed } from '@/lib/timing';
import { THEME_COLOR } from '@/lib/brand';
import { RegisterServiceWorker } from '@/components/RegisterServiceWorker';
import { CommandPalette } from '@/components/CommandPalette';

/**
 * The studio's typefaces, served from this repository (FB-223).
 *
 * These were `next/font/google`, which **downloads the font files from Google at build time**. That put
 * a third party on the critical path of a required check, and twice on 2026-09-29 it failed:
 *
 *     An error occurred in `next/font`.
 *     TypeError: Cannot read properties of null (reading '1')
 *     > Build failed because of webpack errors
 *
 * Both times on pull requests that changed only markdown, and both times green on the next run. The
 * message never mentions the network, so it reads as "your branch broke the build" — which is why it took
 * four checks to exonerate a two-file change, and why it trained me to merge past a red gate. It worked:
 * I merged #291 while that check was failing.
 *
 * A required gate that fails for reasons unrelated to the change teaches people to ignore it, and a gate
 * people ignore is the one that let FB-124 ship a studio with two navigations and a 250px rail on a phone.
 * So the dependency is removed rather than retried: 204 KB of woff2 in `app/fonts/`, and a build that
 * needs no network at all.
 *
 * The exact files Google serves for the **latin** subset, fetched once and committed. Source Serif and
 * Inter are variable fonts, so one file each covers every weight we use; Plex Mono ships a file per weight.
 * The build now ships **4** font files where it shipped 23 — the other 19 were subsets nothing renders.
 *
 * **The typefaces are the same and the measurements moved slightly.** Fifteen of the thirty-four captured
 * screens got between 1% and 7% shorter, every one of them shorter and none taller, because a variable
 * font replaces the static instances Next was requesting and its line boxes are fractionally tighter.
 * Two screens were looked at rather than trusted to the numbers — a desktop page and a phone one — and the
 * type is right on both: serif headings, Inter body, Plex Mono eyebrows, no system fallback. A fallback is
 * what "every screen got shorter" would look like if this had gone wrong, which is why it was checked.
 */
const serif = localFont({
  src: [{ path: './fonts/source-serif-4-latin.woff2', style: 'normal' }],
  weight: '400 500',
  display: 'swap',
  variable: '--font-source-serif',
});
const sans = localFont({
  src: [{ path: './fonts/inter-latin.woff2', style: 'normal' }],
  weight: '100 900',
  display: 'swap',
  variable: '--font-inter',
});
const mono = localFont({
  src: [
    { path: './fonts/ibm-plex-mono-400-latin.woff2', weight: '400', style: 'normal' },
    { path: './fonts/ibm-plex-mono-500-latin.woff2', weight: '500', style: 'normal' },
  ],
  display: 'swap',
  variable: '--font-plex-mono',
});

export const metadata: Metadata = {
  title: 'Foundry Studio',
  description: 'Bruntsfield Foundry Studio — launch and run co-created ventures.',
  // FB-141: the pocket studio, installable. iOS reads `apple-touch-icon` and ignores the manifest's
  // icons; Android reads the manifest. Both are generated by scripts/make-icons.mjs.
  manifest: '/manifest.webmanifest',
  appleWebApp: { capable: true, title: 'Foundry', statusBarStyle: 'default' },
  icons: { icon: '/icon-192.png', apple: '/apple-touch-icon.png' },
};

// FB-009: usable on a phone. Explicit viewport so mobile scaling is correct.
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // FB-141: the installed studio's status bar matches the rail behind it rather than defaulting to
  // white, which on a phone reads as a browser chrome the app forgot to remove.
  themeColor: THEME_COLOR,
};

/**
 * Four places, each named for what the founder is doing there (FB-067).
 *
 * The header used to offer eight, three of which — Ventures, Workstreams, Foundry — sat next to each
 * other and could not be told apart from the words. They described how the software is organised,
 * not what a founder came to do.
 *
 * Two are gone from the header and neither is deleted:
 *
 *  - **Workstreams** (`/lanes`) was a cross-venture view of the same lanes the venture board already
 *    shows. It is reachable, and nothing links to it from a founder's header.
 *  - **Foundry** (`/foundry`) is the story of how the studio works. It belongs where people are
 *    deciding whether to join, not in a working founder's header — the ticket says the public site,
 *    and there is no public site yet, so it moves to the handbook rather than nowhere.
 *
 * The composer is deliberately absent: after FB-065 it is something you do from your venture, not a
 * place you visit.
 *
 * The names deliberately match the page headings — "Needs you" and "What has been happening" — so a
 * founder who clicks a word arrives somewhere that uses the same word (FB-076, FB-080).
 */
const NAV = (isAdmin: boolean, needsHref: string) => [
  // An admin genuinely is choosing between ventures; a founder has one and is going to theirs.
  { href: '/', label: isAdmin ? 'All ventures' : 'Your venture' },
  { href: needsHref, label: 'Needs you', badge: true },
  { href: '/activity', label: 'What happened' },
  { href: '/handbook', label: 'Handbook' },
];

/**
 * The count beside "Needs you", loaded off the critical path (FB-151).
 *
 * ## What was measured
 *
 * On production, signed in as ARCA's founder, `/login` — which renders this layout and a sign-in
 * form, and has no rail — took **5,354 ms**. The same route signed out took **196 ms**. The only
 * difference between those two numbers is the signed-in block of this layout, and the expensive
 * half of it is `loadAccessibleAttention`: open work across every venture the viewer can see, read
 * in the ROOT layout, on **every page of the studio**.
 *
 * FB-151 was written believing the rail was the five seconds. It was not; the rail was simply
 * present on the screens that got measured, and `/login` has never had one.
 *
 * ## Why streaming rather than a faster read
 *
 * Nothing above the fold depends on it. A number beside a link is not worth a blank screen, so the
 * shell flushes immediately and this arrives when it arrives. The read itself is unchanged — same
 * call, same per-venture cache, same FB-083 budget. What changed is that the founder stops waiting
 * for it.
 *
 * ## Why it renders nothing rather than a zero
 *
 * A zero here is a claim that nothing needs the founder, and this studio has learned what an
 * invented number does once it is on a screen (FB-124). Until the count is known there is no badge.
 */
async function AttentionBadge({ email, ventureId }: { email: string; ventureId: string | null }) {
  let count = 0;
  try {
    // FB-149: a founder's "Needs you" is their venture's, so it states the rail's own number — open
    // work AND sends waiting on them — read by the rail's own loader. Anyone seeing several ventures
    // gets the cross-venture page's own number, from the same loader that page lists: open work and
    // waiting sends, summed venture by venture with the rule the desks use.
    const venture = ventureId ? loadVentures().find((v) => v.id === ventureId) : undefined;
    // The email is deliberately NOT recorded as the reading's detail: the ring is process-global and
    // read by an admin, and a diagnostic is no place to accumulate who was signed in.
    count = venture
      ? (await loadRailData(venture)).needsYou
      : (await timed('root layout: what waits on you across your ventures', () => loadAccessibleNeedsYou(email)))
          .count;
  } catch {
    // Guarded — the header must never take down every page when the code host is unreachable.
    count = 0;
  }
  if (count === 0) return null;
  return (
    <span className="tag tag-accent" data-testid="nav-attention-badge" style={{ marginLeft: '0.35rem', padding: '0.05rem 0.35rem' }}>
      {count}
    </span>
  );
}

export default async function RootLayout({ children }: { children: ReactNode }) {
  const session = await auth();
  const email = session?.user?.email;

  // Stays on the critical path deliberately: this reads the manifests off local disk, which is the
  // same read every venture page already makes and is not where the five seconds were. Deferring it
  // would buy nothing and would change the first nav row's word under the reader a beat after they
  // looked at it. Never fatal — a header that throws takes every page with it.
  let isAdmin = false;
  let needs = headerNeedsYou({ isAdmin: false, ventureIds: [] });
  if (email) {
    try {
      const access = authorizeVentures(email, loadVentures(), parseAdminEmails(process.env.STUDIO_ADMIN_EMAILS));
      isAdmin = access.isAdmin;
      needs = headerNeedsYou(access);
    } catch {
      isAdmin = false;
    }
  }

  return (
    <html lang="en" className={`${serif.variable} ${sans.variable} ${mono.variable}`}>
      <body>
        {/* FB-179: "Go to anything" — ⌘K / Ctrl-K, and the first thing Tab reaches. Signed in only:
            there is nothing to go to from the sign-in page. */}
        {email ? <CommandPalette /> : null}
        <header className="topbar">
          <Link href="/" className="wordmark" aria-label="Foundry Studio home">
            <span className="wordmark-name">Bruntsfield</span>
            <span className="wordmark-sub">Foundry</span>
          </Link>
          {/* FB-067: the `03` was a section number from the Bruntsfield marketing site. It means
              something there and nothing here. */}
          <span className="eyebrow topbar-spacer topbar-eyebrow">Foundry Studio</span>
          {email ? (
            <>
              <nav className="topnav" data-testid="topnav">
                {NAV(isAdmin, needs.href).map((n) => (
                  <Link key={n.href} className="pill" href={n.href}>
                    {n.label}
                    {/* The one expensive thing in this header, and the only thing that waits.
                        `fallback={null}` because there is no honest placeholder for a count — a
                        zero would be a claim, and a spinner beside a word is noise. */}
                    {'badge' in n ? (
                      <Suspense fallback={null}>
                        <AttentionBadge email={email} ventureId={needs.venture} />
                      </Suspense>
                    ) : null}
                  </Link>
                ))}
              </nav>
              <form
                className="signout-form"
                action={async () => {
                  'use server';
                  await signOut({ redirectTo: '/login' });
                }}
              >
                <button className="btn" type="submit" title={email}>
                  Sign out
                </button>
              </form>
            </>
          ) : (
            /* Signed-out (login / not-authorized only, FB-015): just the wordmark, no nav. */
            <span className="topnav signout-form" data-testid="topnav-signedout" />
          )}
        </header>
        <main className="main">{children}</main>
        <RegisterServiceWorker />
      </body>
    </html>
  );
}
